version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      DB_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      -"5432:5432"
    volumes:
      -./postgres:/var/lib/postgresql/data